import '@/shared/styles/global.css';
import type { Metadata } from 'next';

import { MontserratFonts } from '@/shared/config/local-font';
import { Layout } from '@/widgets/layout';

export const metadata: Metadata = {
	title: 'Simple To Do List',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en">
			<body className={MontserratFonts.className}>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
};

export default RootLayout;
